// src/components/ProjectModal.vue
<template>
  <div class="fixed inset-0 z-40 flex items-center justify-center p-4" @keydown.esc="$emit('close')">
    <div class="absolute inset-0 bg-black/40" @click="$emit('close')"></div>

    <div class="relative bg-white rounded-2xl shadow-xl max-w-2xl w-full p-6 z-50">
      <div class="flex items-start gap-4">
        <img v-if="project.icon" :src="project.icon" alt="icon" class="w-12 h-12 rounded-full object-cover border"/>
        <div>
          <h3 class="text-xl font-semibold">{{ project.title }}</h3>
          <p class="text-sm text-gray-500">{{ project.slug }}</p>
        </div>
        <button @click="$emit('close')" class="ml-auto text-gray-400 hover:text-gray-700">Close</button>
      </div>

      <hr class="my-4"/>

      <div>
        <h4 class="text-sm font-semibold text-gray-700 mb-1">Problem</h4>
        <p class="text-gray-700 mb-3">{{ project.caseStudy.problem }}</p>

        <h4 class="text-sm font-semibold text-gray-700 mb-1">Solution</h4>
        <p class="text-gray-700 mb-3">{{ project.caseStudy.solution }}</p>

        <h4 class="text-sm font-semibold text-gray-700 mb-1">Impact</h4>
        <p class="text-gray-700 mb-3">{{ project.caseStudy.impact }}</p>

        <div class="mt-4 flex gap-3">
          <a :href="project.link" target="_blank" class="px-4 py-2 rounded-full bg-blue-600 text-white">Open demo</a>
          <a v-if="project.repo" :href="project.repo" target="_blank" class="px-4 py-2 rounded-full border">View repo</a>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
    const props = defineProps({ project: { type: Object, required: true } })
</script>

// src/components/portfolio/ProjectModal.jsx
import React, { useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ExternalLink, Github, AlertCircle, Lightbulb, TrendingUp } from 'lucide-react';

export default function ProjectModal({ project, isOpen, onClose }) {
  const modalRef = useRef(null);
  const closeButtonRef = useRef(null);

  useEffect(() => {
    if (isOpen) {
      closeButtonRef.current?.focus();
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!project) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
            onClick={onClose}
            aria-hidden="true"
          />
          
          <motion.div
            ref={modalRef}
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="relative w-full max-w-2xl max-h-[90vh] overflow-auto bg-white rounded-3xl shadow-2xl"
            role="dialog"
            aria-modal="true"
            aria-labelledby="modal-title"
          >
            {/* Header */}
            <div className="sticky top-0 z-10 bg-white/95 backdrop-blur-sm border-b border-slate-100 p-6 flex items-start justify-between">
              <div className="flex items-center gap-4">
                <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center border border-blue-100">
                  {project.icon && (
                    <img 
                      src={project.icon} 
                      alt=""
                      className="w-10 h-10 object-contain"
                    />
                  )}
                </div>
                <div>
                  <h2 id="modal-title" className="text-xl font-bold text-slate-800">
                    {project.title}
                  </h2>
                  <span className="text-sm text-blue-600 font-medium">{project.slug}</span>
                </div>
              </div>
              
              <button
                ref={closeButtonRef}
                onClick={onClose}
                className="p-2 rounded-xl text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500"
                aria-label="Close modal"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            {/* Content */}
            <div className="p-6 space-y-6">
              <p className="text-slate-600 leading-relaxed">
                {project.description}
              </p>
              
              {/* Tech Stack */}
              <div>
                <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-3">
                  Technologies
                </h3>
                <div className="flex flex-wrap gap-2">
                  {project.tech.map((tech) => (
                    <span 
                      key={tech}
                      className="px-3 py-1.5 rounded-lg bg-blue-50 text-blue-700 text-sm font-medium border border-blue-100"
                    >
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
              
              {/* Case Study */}
              {project.caseStudy && (
                <div className="space-y-4">
                  <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">
                    Case Study
                  </h3>
                  
                  <div className="space-y-4">
                    <div className="p-4 rounded-2xl bg-red-50 border border-red-100">
                      <div className="flex items-center gap-2 mb-2">
                        <AlertCircle className="w-4 h-4 text-red-500" />
                        <span className="text-sm font-semibold text-red-700">Problem</span>
                      </div>
                      <p className="text-sm text-red-800">{project.caseStudy.problem}</p>
                    </div>
                    
                    <div className="p-4 rounded-2xl bg-blue-50 border border-blue-100">
                      <div className="flex items-center gap-2 mb-2">
                        <Lightbulb className="w-4 h-4 text-blue-500" />
                        <span className="text-sm font-semibold text-blue-700">Solution</span>
                      </div>
                      <p className="text-sm text-blue-800">{project.caseStudy.solution}</p>
                    </div>
                    
                    <div className="p-4 rounded-2xl bg-green-50 border border-green-100">
                      <div className="flex items-center gap-2 mb-2">
                        <TrendingUp className="w-4 h-4 text-green-500" />
                        <span className="text-sm font-semibold text-green-700">Impact</span>
                      </div>
                      <p className="text-sm text-green-800">{project.caseStudy.impact}</p>
                    </div>
                  </div>
                </div>
              )}
              
              {/* Actions */}
              <div className="flex flex-wrap gap-3 pt-4 border-t border-slate-100">
                <a
                  href={project.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-blue-600 text-white font-medium hover:bg-blue-700 transition-colors shadow-lg shadow-blue-500/20 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                  <ExternalLink className="w-4 h-4" />
                  View Live Project
                </a>
                <a
                  href={project.repo}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-100 text-slate-700 font-medium hover:bg-slate-200 transition-colors focus:outline-none focus:ring-2 focus:ring-slate-500 focus:ring-offset-2"
                >
                  <Github className="w-4 h-4" />
                  Source Code
                </a>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
