// src/components/ProjectCard.vue
<template>
  <article class="relative bg-white p-6 rounded-2xl shadow-sm hover:shadow-2xl transition-transform transform hover:-translate-y-1 group flex flex-col h-full"
           tabindex="0" @keydown.enter="openDemo" @click="openDemo" role="button" :aria-label="`Open ${project.title}`">
    <!-- circle icon -->
    <div class="absolute -top-5 -left-5 w-14 h-14 rounded-full border-4 border-white shadow-md overflow-hidden bg-white z-20 flex items-center justify-center">
      <img v-if="project.icon" :src="project.icon" :alt="project.title + ' icon'" class="w-full h-full object-cover"/>
      <div v-else class="text-sm font-semibold text-gray-700">{{ initials(project.title) }}</div>
    </div>

    <header class="mb-2 mt-6">
      <h3 class="text-lg font-semibold text-gray-900">{{ project.title }}</h3>
      <p class="text-xs text-gray-500 mt-1">{{ project.slug }}</p>
    </header>

    <p class="text-sm text-gray-600 grow" v-html="project.description"></p>

    <div class="flex flex-wrap gap-2 mt-4">
      <span v-for="(t, i) in project.tech" :key="i" class="text-xs px-3 py-1 rounded-full border bg-white/70">
        {{ t }}
      </span>
    </div>

    <div class="mt-4 flex items-center justify-between">
      <a :href="project.link" @click.stop target="_blank" class="px-3 py-2 rounded-lg bg-blue-50 text-blue-600 font-semibold hover:bg-blue-100">Live demo</a>
      <div class="flex items-center gap-3">
        <button v-if="project.repo" @click.stop="openRepo" class="text-sm text-blue-800">View repo</button>
          |
        <button @click.stop="openCase" class="text-sm text-blue-800">Case study</button>
      </div>
    </div>
  </article>
</template>

<script setup>
  import { defineEmits } from 'vue'

  const props = defineProps({
    project: { type: Object, required: true }
  })

  const emit = defineEmits(['open-case'])

  const openDemo = () => {
    if (props.project.link) window.open(props.project.link, '_blank')
  }

  const openRepo = () => {
    if (props.project.repo) window.open(props.project.repo, '_blank')
  }

  const openCase = () => emit('open-case', props.project)
  const initials = (s = '') => s.split(/\s+/).map(n => n[0]).slice(0,2).join('').toUpperCase()
</script>

// src/components/portfolio/ProjectCard.jsx
import React from 'react';
import { motion } from 'framer-motion';
import { ExternalLink, Github, Layers } from 'lucide-react';

export default function ProjectCard({ project, index, onClick }) {
  return (
    <motion.article
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: index * 0.1 }}
      className="group flex flex-col justify-between bg-white rounded-3xl p-6 shadow-xl shadow-slate-200/50 border border-slate-200 hover:shadow-2xl hover:shadow-blue-100/50 hover:border-blue-200 transition-all duration-300 cursor-pointer focus-within:ring-2 focus-within:ring-blue-500 focus-within:ring-offset-2"
      onClick={onClick}
      onKeyDown={(e) => e.key === 'Enter' && onClick()}
      tabIndex={0}
      role="button"
      aria-label={`View ${project.title} case study`}
    >
      <div>
        <div className="flex items-start justify-between mb-4">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center overflow-hidden border border-blue-100">
            {project.icon ? (
              <img 
                src={project.icon} 
                alt={`${project.title} icon`}
                className="w-8 h-8 object-contain"
                onError={(e) => {
                  e.target.style.display = 'none';
                  e.target.nextSibling.style.display = 'flex';
                }}
              />
            ) : null}
            <Layers className="w-6 h-6 text-blue-500" style={{ display: project.icon ? 'none' : 'block' }} />
          </div>
          
          <span className="px-2.5 py-1 rounded-lg bg-blue-50 text-blue-600 text-xs font-medium">
            {project.slug}
          </span>
        </div>
        
        <h3 className="text-lg font-bold text-slate-800 mb-2 group-hover:text-blue-600 transition-colors">
          {project.title}
        </h3>
        
        <p className="text-slate-600 text-sm leading-relaxed mb-4 line-clamp-2">
          {project.description}
        </p>
        
        <div className="flex flex-wrap gap-1.5 mb-4">
          {project.tech.slice(0, 4).map((tech) => (
            <span 
              key={tech}
              className="px-2 py-0.5 rounded-md bg-slate-100 text-slate-600 text-xs font-medium"
            >
              {tech}
            </span>
          ))}
          {project.tech.length > 4 && (
            <span className="px-2 py-0.5 rounded-md bg-slate-100 text-slate-500 text-xs">
              +{project.tech.length - 4}
            </span>
          )}
        </div>
      </div>
      
      <div className="flex items-center gap-3 pt-4 border-t border-slate-200">
        <a
          href={project.link}
          target="_blank"
          rel="noopener noreferrer"
          onClick={(e) => e.stopPropagation()}
          className="inline-flex items-center gap-1.5 text-sm text-blue-600 font-medium hover:text-blue-700 transition-colors focus:outline-none focus:underline"
          aria-label={`Visit ${project.title} live site`}
        >
          <ExternalLink className="w-4 h-4" />
          Live
        </a>
        <a
          href={project.repo}
          target="_blank"
          rel="noopener noreferrer"
          onClick={(e) => e.stopPropagation()}
          className="inline-flex items-center gap-1.5 text-sm text-slate-600 font-medium hover:text-slate-800 transition-colors focus:outline-none focus:underline"
          aria-label={`View ${project.title} source code`}
        >
          <Github className="w-4 h-4" />
          Code
        </a>
      </div>
    </motion.article>
  );
}
