// src/components/portfolio/ExperienceCard.jsx
import React from 'react';
import { motion } from 'framer-motion';
import { Briefcase, Calendar, Building2 } from 'lucide-react';
import InfoCard from './InfoCard';
import  portfolioData  from './PortfolioData';

export default function ExperienceCard() {
  const { experience } = portfolioData;

  return (
    <InfoCard delay={0.2} className="col-span-1 md:col-span-2">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2.5 rounded-xl bg-blue-100 text-blue-600">
          <Briefcase className="w-5 h-5" />
        </div>
        <h2 className="text-xl font-bold text-slate-800">Experience</h2>
      </div>
      
      <div className="space-y-6">
        {experience.map((exp, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.4, delay: index * 0.1 }}
            className="relative pl-6 border-l-2 border-blue-200 last:border-l-blue-100"
          >
            <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-blue-500 border-4 border-white shadow-sm" />
            
            <div className="pb-6 last:pb-0">
              <h3 className="text-lg font-semibold text-slate-800">{exp.title}</h3>
              
              <div className="flex flex-wrap items-center gap-3 mt-1 mb-3">
                <span className="inline-flex items-center gap-1.5 text-sm text-blue-600 font-medium">
                  <Building2 className="w-3.5 h-3.5" />
                  {exp.company}
                </span>
                <span className="inline-flex items-center gap-1.5 text-sm text-slate-500">
                  <Calendar className="w-3.5 h-3.5" />
                  {exp.duration}
                </span>
              </div>
              
              <p className="text-slate-600 text-sm leading-relaxed">
                {exp.description}
              </p>
            </div>
          </motion.div>
        ))}
      </div>
    </InfoCard>
  );
}

// src/components/ExperienceCard.vue
<template>
  <section id="experience" class="py-12 bg-gray-50">
    <div class="max-w-4xl mx-auto px-4">
      <h2 class="text-3xl font-bold mb-6">Experience</h2>
      <div class="space-y-4">
        <article v-for="(item, idx) in data.experience" :key="idx" class="bg-white border rounded-xl p-4 sm:p-6 shadow-sm flex gap-4 items-start">
          <div class="flex-shrink-0">
            <div class="w-12 h-12 rounded-full bg-gradient-to-br from-blue-100 to-indigo-100 flex items-center justify-center text-sm font-semibold">
              {{ initials(item.company) }}
            </div>
          </div>
          <div>
            <div class="flex items-baseline gap-3">
              <h3 class="text-lg font-semibold">{{ item.title }}</h3>
              <span class="text-sm text-gray-500">{{ item.company }}</span>
            </div>
            <div class="text-xs text-gray-400 mb-2">{{ item.duration }}</div>
            <p class="text-gray-700 text-sm">{{ item.description }}</p>
          </div>
        </article>
      </div>
    </div>
  </section>
</template>

<script setup>
    import data from '../data.json'
    const initials = (s = '') => s.split(/\s+/).map(n => n[0]).slice(0,2).join('').toUpperCase()
</script>
