// src/components/portfolio/Footer.jsx
import React from 'react';
import { portfolioData } from './PortfolioData';

export default function Footer() {
  const { name } = portfolioData;
  const currentYear = new Date().getFullYear();

  return (
    <footer className="mt-12 py-8 border-t border-slate-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <p className="text-center text-slate-500 text-sm">
          © {currentYear} {name}. All rights reserved.
        </p>
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer class="py-6 bg-white border-t">
    <div class="max-w-6xl mx-auto px-4 text-center text-sm text-gray-500">
      <div class="mb-2">
        <a href="#profile" @click.prevent="scrollTo('#profile')" class="font-medium text-gray-700">{{ data.name }}</a> • Fullstack Developer
      </div>
      <div>&copy; {{ new Date().getFullYear() }} {{ data.name }}. All rights reserved.</div>
    </div>
  </footer>
</template>

<script setup>
  import data from '../data.json'
  const scrollTo = (id) => {
    const el = document.querySelector(id)
    if (el) el.scrollIntoView({ behavior: 'smooth' })
  }
</script>
