// src/App.jsx
import { About, Footer, Header, Skills, Testimonial, Work } from "./container";
import { Navbar } from "./components";
import './App.scss'
import React from 'react'

function App() {
  return (
    <>
        <div className="app">
            <Header />
            <About />
            <Work />
            <Skills />
            <Testimonial />
            <Footer />
        </div>
    </>
  )
}

export default App

// src/App.vue
<script setup>
  import Header from './components/Header.vue'
  import Hero from './components/Hero.vue'
  import About from './components/About.vue'
  import ExperienceCard from './components/ExperienceCard.vue'
  import ProjectsSection from './components/ProjectsSection.vue'
  import Contact from './components/Contact.vue'
  import Footer from './components/Footer.vue'
</script>

<template>
  <Header />
  <Hero />
  <About />
  <ExperienceCard />
  <ProjectsSection />
  <Contact />
  <Footer />
</template>
